import { Insight, InsightApiResponse, UserRole } from '../types';
import { getInsightsByRole, refreshInsightsByRole, ROLE_INSIGHTS } from '../data/dummyInsights';

// ============================================================
// FUTURE FASTAPI CONNECTION
// ============================================================
// This function will fetch real recommendations from FastAPI.
//
// ⚠️ BEFORE USING:
// 1. Make sure the FastAPI backend server is running:
//    uvicorn main:app --reload
// 2. Make sure GET /insights exists and returns HTTP 200.
// 3. Make sure the API returns data matching the Insight type.
// ============================================================

// 📍 CHANGE THIS URL IF YOUR FASTAPI SERVER USES A DIFFERENT PORT
const FASTAPI_ENDPOINT = "http://127.0.0.1:8000/insights";

/**
 * Fetches real recommendations generated by your colleague's
 * `generate_recommendations()` via FastAPI.
 */
export async function fetchInsights(role?: UserRole): Promise<Insight[]> {
  const url = role ? `${FASTAPI_ENDPOINT}?role=${encodeURIComponent(role)}` : FASTAPI_ENDPOINT;
  const response = await fetch(url);

  if (!response.ok) {
    throw new Error(
      `Failed to fetch insights from FastAPI (${url}): ${response.status} ${response.statusText}`
    );
  }

  const data: Insight[] = await response.json();
  return data;
}

/**
 * InSightAI Data Service
 */
export const insightService = {
  /**
   * Fetches latest insights for the selected user role.
   */
  async getLatestInsights(role: UserRole = 'HR'): Promise<Insight[]> {
    // ============================================================
    // 🔵 CURRENTLY ACTIVE — USING ROLE-BASED DUMMY DATA
    // ============================================================
    // The application currently uses dummy insights partitioned by role.
    // Keep this until the FastAPI backend is connected.
    //
    // FLOW: Login (Role) -> Dashboard -> ROLE_INSIGHTS[role] -> Beautiful UI Cards
    return await getInsightsByRole(role);

    // ============================================================
    // 🟢 FUTURE STEP — UNCOMMENT THIS WHEN FASTAPI IS READY
    // ============================================================
    // FLOW: Login (Role) -> Dashboard -> GET /insights?role={role} -> FastAPI -> RAG Pipeline -> UI Cards
    /*
    const insights = await fetchInsights(role);
    return insights;
    */
  },

  /**
   * Simulates refreshing latest insights for the selected user role.
   */
  async refreshInsights(role: UserRole = 'HR'): Promise<Insight[]> {
    return await refreshInsightsByRole(role);
  },

  /**
   * Helper endpoint formatted for API response wrapper contracts
   */
  async getInsightsApiResponse(role: UserRole = 'HR'): Promise<InsightApiResponse> {
    const data = await this.getLatestInsights(role);
    return {
      success: true,
      count: data.length,
      lastUpdated: new Date().toISOString(),
      data
    };
  }
};



